============================= test session starts ==============================
platform darwin -- Python 3.12.7, pytest-8.0.0, pluggy-1.5.0 -- /opt/anaconda3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/Users/shoru/Desktop/AML_git/Applied-Machine-Learning/Assignment3/.hypothesis/examples'))
rootdir: /Users/shoru/Desktop/AML_git/Applied-Machine-Learning/Assignment3
plugins: hypothesis-6.127.6, cov-4.1.0, anyio-4.2.0, hydra-core-1.3.2
collecting ... collected 2 items

test.py::test_score ERROR                                                [ 50%]
test.py::test_flask FAILED                                               [100%]

==================================== ERRORS ====================================
_________________________ ERROR at setup of test_score _________________________

    @pytest.fixture
    def model_fixture():
        print("Loading model...")
        try:
>           model, vectorizer = load_model()

test.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
score.py:8: in load_model
    model = mlflow.sklearn.load_model("runs:/6d1fd6bfb2d140de8c9555d37933eda3/artifacts/random_forest_model")
/opt/anaconda3/lib/python3.12/site-packages/mlflow/sklearn/__init__.py:613: in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py:100: in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py:117: in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py:74: in get_artifact_repository
    return repository(artifact_uri)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py:26: in __init__
    uri = RunsArtifactRepository.get_underlying_uri(artifact_uri)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py:39: in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py:47: in get_artifact_uri
    run = store.get_run(run_id)
/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py:659: in get_run
    run_info = self._get_run_info(run_id)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mlflow.store.tracking.file_store.FileStore object at 0x3096b1bb0>
run_uuid = '6d1fd6bfb2d140de8c9555d37933eda3'

    def _get_run_info(self, run_uuid):
        """
        Note: Will get both active and deleted runs.
        """
        exp_id, run_dir = self._find_run_root(run_uuid)
        if run_dir is None:
>           raise MlflowException(
                f"Run '{run_uuid}' not found", databricks_pb2.RESOURCE_DOES_NOT_EXIST
            )
E           mlflow.exceptions.MlflowException: Run '6d1fd6bfb2d140de8c9555d37933eda3' not found

/opt/anaconda3/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py:683: MlflowException
---------------------------- Captured stdout setup -----------------------------
Loading model...
Error loading model: Run '6d1fd6bfb2d140de8c9555d37933eda3' not found
=================================== FAILURES ===================================
__________________________________ test_flask __________________________________

    def test_flask():
        print("Starting Flask test...")
        os.system("python app.py &")
        time.sleep(2)
        try:
            response = requests.post(
                "http://localhost:5000/score",
                json={"text": "Test message", "threshold": 0.5}
            )
>           assert response.status_code == 200
E           assert 403 == 200
E            +  where 403 = <Response [403]>.status_code

test.py:52: AssertionError
----------------------------- Captured stdout call -----------------------------
Starting Flask test...
=============================== warnings summary ===============================
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google.protobuf.pyext._message.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google.protobuf.pyext._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

../../../../../../opt/anaconda3/lib/python3.12/site-packages/mlflow/utils/requirements_utils.py:20
  /opt/anaconda3/lib/python3.12/site-packages/mlflow/utils/requirements_utils.py:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources  # noqa: TID251

../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
  /opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
  /opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
  /opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../../opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154
  /opt/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

test.py::test_score
  /opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.5.1 when using version 1.4.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

test.py::test_score
  /opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.5.1 when using version 1.4.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform darwin, python 3.12.7-final-0 ----------
Name       Stmts   Miss  Cover   Missing
----------------------------------------
score.py      13      5    62%   9, 12-15
----------------------------------------
TOTAL         13      5    62%

=========================== short test summary info ============================
FAILED test.py::test_flask - assert 403 == 200
ERROR test.py::test_score - mlflow.exceptions.MlflowException: Run '6d1fd6bfb...
=================== 1 failed, 13 warnings, 1 error in 5.44s ====================
